FROM openjdk:17-slim
WORKDIR /app
COPY Subscriber/target/subscriber-1.0-SNAPSHOT.jar subscriber.jar
COPY wait-for-rabbitq.sh /usr/local/bin/wait-for-rabbitmq.sh
RUN chmod +x /usr/local/bin/wait-for-rabbitmq.sh
RUN apt-get update && apt-get install -y netcat
ENTRYPOINT ["/usr/local/bin/wait-for-rabbitmq.sh", "rabbitmq", "java", "-jar", "subscriber.jar"]
